
include:
  - services/postgres.yaml
  - services/celery_workers.yaml
  - services/notification_service.yaml
  - ../analysis_service/deployment/docker-compose.yaml
  - ../data_collection_service/deployment/docker-compose.yaml
  - ../lan-Webapp/deployment/docker-compose.yaml

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_smtp
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - analysis_network

  redis:
    image: redis:7-alpine
    container_name: redis_queue
    ports:
      - "6379:6379"
    networks:
      - analysis_network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_host
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./email-templates:/etc/nginx/html/templates:ro
    networks:
      - analysis_network
    depends_on:
      - analysis_service
      - data_collection_service
      - redis
      - notification_service

networks:
  analysis_network:
    driver: bridge