
include:
  - services/postgres.yaml
  - services/celery_workers.yaml
  - ../Analytics-Service/deployment/docker-compose.yaml
  - ../Ingestion-Service/deployment/docker-compose.yaml
  - ../Reporting-Service/deployment/docker-compose.yaml

services:
  redis:
    image: redis:7-alpine
    container_name: redis_queue
    networks:
      - analysis_network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_host
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx-ssl.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - analysis_network
    depends_on:
      - analytics_service
      - ingestion_service
      - reporting_service
      - redis

networks:
  analysis_network:
    driver: bridge